# Generated by Django 3.2.3 on 2021-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatures',
            name='post',
            field=models.ManyToManyField(related_name='feature', to='Shop.Post'),
        ),
    ]
