# Generated by Django 3.2.3 on 2021-05-30 08:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_post_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я клієна")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище клієна')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
            ],
        ),
    ]
