# Generated by Django 3.2.3 on 2021-05-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_callrequests_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequests',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Запитання'),
        ),
    ]
